spring:
 datasource:
  url: jdbc:mysql://review-room.cfb1unbcvrs4.us-east-1.rds.amazonaws.com:3306/sungjin-review-room?useSSL=false&serverTImezone=UTC
  username: admin
  password: flqbdjemals
 data:
  rest:
    base-path: /api

server:
    port: 8080