spring:
 datasource:
  url: jdbc:mysql://review-room.cfb1unbcvrs4.us-east-1.rds.amazonaws.com:3306/sungjin-review-room?useSSL=false&serverTImezone=UTC
  username: admin
  password: flqbdjemals
 data:
  rest:
    base-path: /api
 messages:
    basename: messages
 jpa:
  show-sql: true
  hibernate:
    ddl-auto: update
 security:
    user:
      password: test123 #임시 로그인 비밀번호. 아이디는 user
    filter:
      order: 10 # For Custom Filter
 mail:
    host: smtp.gmail.com
    port: 465
    protocol: smtp
    username: sungjin.reviewroom@gmail.com
    password: wlliuacgjtdzctsf
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
# App Properties
sungjin:
  reviewroom:
    app:
     jwtSecret: sungjinReviewRoomSecretKey  
     jwtExpirationMs: 600000 #10분
     jwtRefreshExpirationMs: 86400000
     jwtCookieName: sungjinJWT
     refreshTokenCookieName: sungjinRefreshToken
     filePath: src/img/items/
     apiPrefix: /api

server:
    port: 8081
